if [ -z "$ENGINEAI_ROBOTICS_DIR" ]; then
    export ENGINEAI_ROBOTICS_DIR="$PWD"
    echo "[INFO] ENGINEAI_ROBOTICS_DIR=$ENGINEAI_ROBOTICS_DIR"

    export ENGINEAI_ROBOTICS_ASSETS="$ENGINEAI_ROBOTICS_DIR/assets"
    echo "[INFO] ENGINEAI_ROBOTICS_ASSETS=$ENGINEAI_ROBOTICS_ASSETS"

    export ENGINEAI_ROBOTICS_THIRD_PARTY="/opt/engineai_robotics_third_party"
    echo "[INFO] ENGINEAI_ROBOTICS_THIRD_PARTY=$ENGINEAI_ROBOTICS_THIRD_PARTY"

    export ENGINEAI_ROBOTICS_HARDWARE="/opt/engineai_robotics_hardware"
    echo "[INFO] ENGINEAI_ROBOTICS_HARDWARE=$ENGINEAI_ROBOTICS_HARDWARE"
    
    export ENGINEAI_ROBOTICS_PLATFORM="mujoco"
    echo "[INFO] ENGINEAI_ROBOTICS_PLATFORM=$ENGINEAI_ROBOTICS_PLATFORM"

    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$ENGINEAI_ROBOTICS_THIRD_PARTY/lib:$ENGINEAI_ROBOTICS_HARDWARE/lib:$ENGINEAI_ROBOTICS_DIR/build/_install/lib"
    echo "[INFO] LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
fi