"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class GamepadKeys(object):
    __slots__ = ["timestamp", "digital_states", "analog_states"]

    __typenames__ = ["int64_t", "int32_t", "double"]

    __dimensions__ = [None, [12], [6]]

    def __init__(self):
        self.timestamp = 0
        self.digital_states = [ 0 for dim0 in range(12) ]
        self.analog_states = [ 0.0 for dim0 in range(6) ]

    def encode(self):
        buf = BytesIO()
        buf.write(GamepadKeys._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>12i', *self.digital_states[:12]))
        buf.write(struct.pack('>6d', *self.analog_states[:6]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != GamepadKeys._get_packed_fingerprint():
            raise ValueError("Decode error")
        return GamepadKeys._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = GamepadKeys()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.digital_states = struct.unpack('>12i', buf.read(48))
        self.analog_states = struct.unpack('>6d', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if GamepadKeys in parents: return 0
        tmphash = (0xd6cae60f8643a772) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if GamepadKeys._packed_fingerprint is None:
            GamepadKeys._packed_fingerprint = struct.pack(">Q", GamepadKeys._get_hash_recursive([]))
        return GamepadKeys._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", GamepadKeys._get_packed_fingerprint())[0]

