# 使用 pd_stand_runner，但禁用严格运动检查
pre_motion_cmd_enable: true

pre_cmd_enable_joints:
  - [0, 0, 0, 0, 0, 0] # left leg
  - [0, 0, 0, 0, 0, 0] # right leg
  - [0] # waist
  - [0, 0, 0, 0, 0, 1, 1] # left arm
  - [0, 0, 0, 0, 0, 0, 0] # left hand
  - [0, 0, 0, 0, 0, 1, 1] # right arm
  - [0, 0, 0, 0, 0, 0, 0] # right hand
  - [0, 0] # head

stiffness:
  - [0, 0, 0, 0, 0, 0] # left leg
  - [0, 0, 0, 0, 0, 0] # right leg
  - [0] # waist
  - [0, 0, 0, 0, 0, 50, 50] # left arm
  - [0, 0, 0, 0, 0, 0, 0] # left hand
  - [0, 0, 0, 0, 0, 50, 50] # right arm
  - [0, 0, 0, 0, 0, 0, 0] # right hand
  - [0, 0] # head

damping:
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0]
